### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by biggerbaby** [calzakk/CyoHash#1] opened 2016-08-11 03:34 UTC
I downloaded CyoHash from github and compiled it using the NSIS Compiler per the instructions. I executed the .exe that was created and completed the install process. When I right click on a file, there is no cychash menu as expected. I tried restarting the machine to no avail. Please help.

**Comment by calzakk** [comment] 2016-08-11 10:28
Which version of Windows are you using?

If you're proficient with the registry, can you see if these keys exists:
- HKEY_CLASSES_ROOT*\shellex\ContextMenuHandlers\CyoHash
- HKEY_CLASSES_ROOT\CLSID{0026FF13-16AE-462B-8C7B-C07DA5CD386E}
- HKEY_CLASSES_ROOT\TypeLib{16E0FFA4-6142-40A7-B385-820D66B71B16}
- HKEY_CLASSES_ROOT\Wow6432Node\TypeLib{16E0FFA4-6142-40A7-B385-820D66B71B16}
- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CyoHash

What happens if you manually execute this file:
C:\Program Files\CyoHash\CyoHash.exe

**Comment by biggerbaby** [comment] 2016-08-11 15:14
Sorry - should have mentioned that. I am using Windows 7 Professional 64 bit. I am not proficient with registry, but I'll look into that next. I tried to execute the .exe, but it does not exist in the directory that I installed the program to.

**Comment by calzakk** [comment] 2016-08-11 20:00
Are there any files in the installation folder?  There should be three files: CyoHash.exe, CyoHash.dll, and Uninstall.exe.

If you re-run the installer, could you right-click the installation details when it says "Installation Complete" and select "Copy Details To Clipboard" then paste here?

Presumably the source code built fine? (both Release|Win32 and Release|x64 configs)

And presumably there were no errors when the NSIS installer built?  Could you rebuild the installer and paste the log output?  Are you using NSIS 3, or an older version?

**Comment by biggerbaby** [comment] 2016-08-15 23:04
I just checked and the only files in the 'install' folder are .gitignore,
InstallNotes text file and CyoHash NSIS Script file. There is also a
'plugin' folder that has 5 files in it. I do not see the three files you
are referring to.

I reran the installer per your request and here is the requested output:

Output folder: C:\Users\User\Downloads
Output folder: C:\Users\User\Downloads\CyoHash-master
Extract: .gitignore
Extract: LICENSE.TXT... 100%
Extract: README.TXT... 100%
Extract: README.md... 100%
Extract: TODO.txt... 100%
Output folder: C:\Users\User\Downloads\CyoHash-master\install
Extract: .gitignore
Extract: CyoHash.nsi... 100%
Extract: InstallNotes.txt... 100%
Output folder: C:\Users\User\Downloads\CyoHash-master\install\plugin
Extract: .gitignore
Extract: plugin.cpp... 100%
Extract: plugin.def... 100%
Extract: plugin.vcxproj... 100%
Extract: plugin.vcxproj.filters... 100%
Output folder: C:\Users\User\Downloads\CyoHash-master\source
Extract: .gitignore
Extract: AboutDlg.cpp... 100%
Extract: AboutDlg.h... 100%
Extract: BrowseDlg.cpp... 100%
Extract: BrowseDlg.h... 100%
Extract: CyoHash.cpp... 100%
Extract: CyoHash.ico... 100%
Extract: CyoHash.rc... 100%
Extract: CyoHash.sln... 100%
Extract: CyoHash.vcxproj... 100%
Extract: CyoHash.vcxproj.filters... 100%
Extract: CyoHashDlg.cpp... 100%
Extract: CyoHashDlg.h... 100%
Extract: CyoHashDlg2.cpp... 100%
Extract: CyoHashDlg2.h... 100%
Extract: Hasher.cpp... 100%
Extract: Hasher.h... 100%
Extract: Messages.h... 100%
Extract: NamedPipeServer.cpp... 100%
Extract: NamedPipeServer.h... 100%
Extract: Utils.h... 100%
Extract: resource.h... 100%
Extract: stdafx.cpp... 100%
Extract: stdafx.h... 100%
Output folder: C:\Users\User\Downloads\CyoHash-master\source\ShellExtension
Extract: .gitignore
Extract: CyoHash.bmp... 100%
Extract: CyoHash.cpp... 100%
Extract: CyoHash.rgs... 100%
Extract: ShellExtension.cpp... 100%
Extract: ShellExtension.def... 100%
Extract: ShellExtension.h... 100%
Extract: ShellExtension.idl... 100%
Extract: ShellExtension.rc... 100%
Extract: ShellExtension.rgs... 100%
Extract: ShellExtension.vcxproj... 100%
Extract: ShellExtension.vcxproj.filters... 100%
Extract: resource.h... 100%
Extract: stdafx.cpp... 100%
Extract: stdafx.h... 100%
Output folder: C:\Users\User\Downloads\CyoHash-master\source\cyoencode
Extract: CyoEncode.c... 100%
Extract: CyoEncode.h... 100%
Extract: LICENSE.TXT... 100%
Output folder: C:\Users\User\Downloads
Completed

I thought everything went fine during the build, but I tried again and got
this output:

MakeNSIS v3.0 - Copyright 1999-2016 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.

Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing default plugins: "C:\Program Files (x86)\NSIS\Plugins\x86-ansi*.
dll"
- Banner::destroy
- Banner::getWindow
- Banner::show
- BgImage::AddImage
- BgImage::AddText
- BgImage::Clear
- BgImage::Destroy
- BgImage::Redraw
- BgImage::SetBg
- BgImage::SetReturn
- BgImage::Sound
- Dialer::AttemptConnect
- Dialer::AutodialHangup
- Dialer::AutodialOnline
- Dialer::AutodialUnattended
- Dialer::GetConnectedState
- InstallOptions::dialog
- InstallOptions::initDialog
- InstallOptions::show
- LangDLL::LangDialog
- Math::Script
- StartMenu::Init
- StartMenu::Select
- StartMenu::Show
- System::Alloc
- System::Call
- System::Copy
- System::Free
- System::Get
- System::Int64Op
- System::Store
- System::StrAlloc
- TypeLib::GetLibVersion
- TypeLib::Register
- TypeLib::UnRegister
- UserInfo::GetAccountType
- UserInfo::GetName
- UserInfo::GetOriginalAccountType
- VPatch::GetFileCRC32
- VPatch::GetFileMD5
- VPatch::vpatchfile
- advsplash::show
- nsDialogs::Create
- nsDialogs::CreateControl
- nsDialogs::CreateItem
- nsDialogs::CreateTimer
- nsDialogs::GetUserData
- nsDialogs::KillTimer
- nsDialogs::OnBack
- nsDialogs::OnChange
- nsDialogs::OnClick
- nsDialogs::OnNotify
- nsDialogs::SelectFileDialog
- nsDialogs::SelectFolderDialog
- nsDialogs::SetRTL
- nsDialogs::SetUserData
- nsDialogs::Show
- nsExec::Exec
- nsExec::ExecToLog
- nsExec::ExecToStack
- nsisdl::download
- nsisdl::download_quiet
- splash::show

!define: "MUI_INSERT_NSISCONF"=""

Changing directory to: "C:\Users\User\Downloads\CyoHash-master\install"

Processing script file:
"C:\Users\User\Downloads\CyoHash-master\install\CyoHash.nsi"
(ACP)
!AddPluginDir: "plugin\Release"
!include: "C:\Program Files (x86)\NSIS\Include\MUI2.nsh" (ACP)
!include: "C:\Program Files (x86)\NSIS\Contrib\Modern UI 2\MUI2.nsh" (ACP)
NSIS Modern User Interface version 2.0 - Copyright 2002-2016 Joost Verburg
(C:\Program Files (x86)\NSIS\Contrib\Modern UI 2\MUI2.nsh:10)
!include: closed: "C:\Program Files (x86)\NSIS\Contrib\Modern UI 2\MUI2.nsh"
!include: closed: "C:\Program Files (x86)\NSIS\Include\MUI2.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\LogicLib.nsh" (ACP)
!include: closed: "C:\Program Files (x86)\NSIS\Include\LogicLib.nsh"
SetCompressor: /FINAL /SOLID LZMA
Name: "CyoHash"
OutFile: "CyoHash.exe"
!define: "PRODUCT_VERSION"="2.2.0"
!define: "FILE_VERSION"="2.2.0.1"
VIAddVersionKey: "FileVersion" "2.2.0.1"
VIAddVersionKey: "ProductVersion" "2.2.0"
VIAddVersionKey: "ProductName" "CyoHash"
VIAddVersionKey: "Comments" ""
VIAddVersionKey: "CompanyName" ""
VIAddVersionKey: "LegalCopyright" "(c) 2009-2016, Graham Bull. All rights
reserved."
VIAddVersionKey: "LegalTrademarks" ""
VIAddVersionKey: "FileDescription" "CyoHash"
VIAddVersionKey: "OriginalFilename" "CyoHash.exe"
Var: "MACHINE_ARCHITECTURE"
Var: "ALREADYINSTALLED"
ShowInstDetails: show
!define: "MUI_ABORTWARNING"=""
!insertmacro: MUI_PAGE_WELCOME
!insertmacro: end of MUI_PAGE_WELCOME
ReserveFile: "InstallNotes.txt" 1012 bytes
Page: custom (creator:NotesPage)
!define: "MUI_PAGE_CUSTOMFUNCTION_PRE"="SkipPageIfAlreadyInstalled"
!insertmacro: MUI_PAGE_DIRECTORY
!insertmacro: end of MUI_PAGE_DIRECTORY
!define: "MUI_COMPONENTSPAGE_NODESC"=""
!insertmacro: MUI_PAGE_COMPONENTS
!insertmacro: end of MUI_PAGE_COMPONENTS
!insertmacro: MUI_PAGE_INSTFILES
!insertmacro: end of MUI_PAGE_INSTFILES
!define: "MUI_FINISHPAGE_NOAUTOCLOSE"=""
!define: "MUI_FINISHPAGE_REBOOTLATER_DEFAULT"=""
!insertmacro: MUI_PAGE_FINISH
!insertmacro: end of MUI_PAGE_FINISH
Section: "CyoHash" ->(MainSection)
SectionIn: [RO]
WriteRegStr: HKLM\Software\CyoHash\=$INSTDIR
SetOutPath: "$INSTDIR"
WriteUninstaller: "$INSTDIR\Uninstall.exe"
SetOverwrite: try
!insertmacro: _If
!insertmacro: end of _If
File: "..\source\x64\Release\CyoHash.exe" -> no files found.
Usage: File [/nonfatal] [/a]([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "C:\Users\User\Downloads\CyoHash-master\install\CyoHash.nsi"
on line 92 -- aborting creation process

Please advise how to proceed.

**Comment by calzakk** [comment] 2016-08-16 11:37
I'm not sure how you built the first installer, but it looks wrong because it's installing the wrong files.

But then, when you try to build the installer again, NSIS is complaining that x64\Release\CyoHash.exe doesn't exist. Did you first build the solution using Visual Studio? (both win32 and x64 release builds?)

I notice that you're using NSIS 3.  I'm still using version 2, because 3 is fairly new and I haven't gotten round to testing CyoHash with that yet.

I've just created a new release that you might be interested in, you can download the pre-built installer via this link instead of trying to create it yourself:
https://github.com/calzakk/CyoHash/releases/tag/2.2.0.1

**Comment by biggerbaby** [comment] 2016-08-16 21:04
Thanks for posting the link. I installed and it works as expected. It
sounds like NSIS 3 is unable to compile CyoHash correctly. Thanks for your
help!

**Comment by calzakk** [comment] 2016-08-24 19:29
I can confirm that the CyoHash installer builds successfully with NSIS 3.0 and runs just fine, so I'm closing this issue.

**Closed as completed by calzakk** 2016-08-24 19:29 UTC
